FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git python3 python3-pip qemu-system-aarch64 qemu-utils qemu-kvm libglib2.0-dev libfdt-dev libpixman-1-dev ca-certificates wget curl sudo \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash emulator && mkdir -p /workspaces
WORKDIR /workspaces

# copy manager and scripts
COPY linux-emulator-server /workspaces/linux-emulator-server
RUN chmod +x /workspaces/linux-emulator-server/src/scripts/*.sh

EXPOSE 8080

ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

CMD ["/workspaces/linux-emulator-server/cmd/manager/manager"]
