apiVersion: apps/v1
kind: Deployment
metadata:
  name: qemu-ios-emulator-manager
  labels:
    app: qemu-ios-emulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qemu-ios-emulator
  template:
    metadata:
      labels:
        app: silicon-emulator
    spec:
      containers:
        - name: manager
          image: qemu-ios-emulator/manager:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: images
              mountPath: /workspaces/images
            - name: logs
              mountPath: /var/log/qemu-ios-emulator
      volumes:
        - name: images
          emptyDir: {}
        - name: logs
          emptyDir: {}
