apiVersion: v1
kind: Service
metadata:
  name: silicon-emulator-service
spec:
  type: ClusterIP
  selector:
    app: silicon-emulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
