#!/bin/sh

# Start the VNC server with the desired resolution and depth
vncserver :1 -geometry 1280x800 -depth 24

# Set the background color and start the window manager
xsetroot -solid grey
startxfce4 &

# Start any additional applications here
# For example, you can start a terminal or a specific application
# xfce4-terminal &

# Keep the script running
wait $!